# Generated by Django 3.2.13 on 2022-05-23 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('branch', models.CharField(choices=[('Trivandrum', 'Trivandrum'), ('Kollam ', 'Kollam'), ('Allapuzha ', 'Allapuzha'), ('Kozhikode ', 'Kozhikode'), ('Ernakulam ', 'Ernakulam'), ('Thrissur ', 'Thrissur'), ('Kasargod ', 'Kasargod')], max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
