# Generated by Django 3.2.13 on 2022-05-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220523_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='Branch',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='Email',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='Name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='PhoneNumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='SubBranch',
            new_name='subbranch',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
