# Generated by Django 3.2.13 on 2022-05-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220523_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='address',
        ),
    ]
