# Generated by Django 3.2.13 on 2022-05-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_ordermodel_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='phonenumber',
            new_name='zip_code',
        ),
    ]
