# Generated by Django 3.2.13 on 2022-05-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
